rancherTurtles:
  image: registry.rancher.com/rancher/rancher-sandbox/rancher-turtles
  tag: v0.3.0
  imagePullPolicy: IfNotPresent
  namespace: rancher-turtles-system
  managerArguments: []
  imagePullSecrets: []
  features:
    embedded-capi:
      disabled: true
    rancher-webhook:
      cleanup: true
      kubectlImage: rancher/kubectl
    rancher-kubeconfigs:
      label: true
cluster-api-operator:
  enabled: true
  cert-manager:
    enabled: false
  cluster-api:
    enabled: true
    version: v1.4.6
    configSecret:
      name: ""
      namespace: ""
      defaultName: capi-env-variables
    core:
      namespace: capi-system
      fetchConfig:
        url: ""
        selector: ""
    kubeadmBootstrap:
      namespace: capi-kubeadm-bootstrap-system
      fetchConfig:
        url: ""
        selector: ""
    kubeadmControlPlane:
      namespace: capi-kubeadm-control-plane-system
      fetchConfig:
        url: ""
        selector: ""
