{{- if .Values.infrastructure }}
# Deploy core, bootstrap, and infrastructure components if not specified
{{- if not .Values.core }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
  name: capi-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "2"
{{- if .Values.secretName }}
spec:
  secretName: {{ .Values.secretName }}
{{- if .Values.secretNamespace }}
  secretNamespace: {{ .Values.secretNamespace }}
{{- end }}
{{- end }}
{{- end }}
{{- if not .Values.bootstrap }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
  name: capi-kubeadm-bootstrap-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: BootstrapProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-bootstrap-system
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "2"
{{- if .Values.secretName }}
spec:
  secretName: {{ .Values.secretName }}
{{- if .Values.secretNamespace }}
  secretNamespace: {{ .Values.secretNamespace }}
{{- end }}
{{- end }}
{{- end }}
{{- if not .Values.controlPlane }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
  name: capi-kubeadm-control-plane-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-control-plane-system
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "2"
{{- if .Values.secretName }}
spec:
  secretName: {{ .Values.secretName }}
{{- if .Values.secretNamespace }}
  secretNamespace: {{ .Values.secretNamespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
